name: Feature Request (Form)
description: Suggest a new feature or enhancement for AutoTrixel
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

    - type: dropdown
      id: component
      attributes:
          label: Component
          description: Which component of AutoTrixel would this feature affect?
          options:
              - Rendering Engine
              - Frontend (Vue)
              - Triangle Generation Logic
              - Canvas/Drawing System
              - Color/Pixel Processing
              - UI/Controls
              - Multiple Components
              - New Component
      validations:
          required: true

    - type: dropdown
      id: feature-type
      attributes:
          label: Feature Type
          description: What type of feature is this?
          options:
              - New Functionality
              - Enhancement/Improvement
              - Performance Optimization
              - User Interface/UX
              - API/Integration
              - Documentation
              - Testing/Quality
      validations:
          required: false

    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description: Is your feature request related to a problem? Please describe.
          placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      validations:
          required: false

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: Describe the solution you'd like to see
          placeholder: A clear and concise description of what you want to happen...
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Describe any alternative solutions or features you've considered
          placeholder: Are there other ways to solve this problem?
      validations:
          required: false

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature?
          options:
              - Critical (Blocking/Essential)
              - High (Important)
              - Medium (Nice to have)
              - Low (Future consideration)
      validations:
          required: false

    - type: textarea
      id: use-cases
      attributes:
          label: Use Cases
          description: Describe specific scenarios where this feature would be used
          placeholder: |
              1. When a user creates triangle-pixel art...
              2. During canvas rendering...
              3. When adjusting color palettes...
      validations:
          required: false

    - type: textarea
      id: technical-details
      attributes:
          label: Technical Details (Optional)
          description: Any technical implementation details, dependencies, or considerations
          placeholder: Technical notes, potential dependencies, architecture considerations...
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, mockups, or examples about the feature request
          placeholder: Any additional information that might help...
      validations:
          required: false

    - type: input
      id: contact
      attributes:
          label: Contact Details (Optional)
          description: How can we reach you if we need more information?
          placeholder: ex. email@example.com
      validations:
          required: false
